### ISSUE TITLE
Error 500 on Vercel

### ISSUE THREAD

**Issue by pmarxbraun** [HPouyanmehr/next-intl-split#2]
Hello @HPouyanmehr 

I got a `Error 500`  when deploying on Vercel

```
The following error occured in loader in next-intl-split. Error: ENOENT: no such file or directory, scandir '/var/task/messages/en'
    at read (node:fs:1399:35)
    at readdirSyncRecursive (node:fs:1437:5)
    at Object.readdirSync (node:fs:1504:12)
    at t.loadI18nTranslations (/var/task/.next/server/chunks/7884.js:76:43453)
    at /var/task/.next/server/chunks/45054.js:1:38767
    at /var/task/.next/server/chunks/7884.js:71:78617
    at /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:185493
    at /var/task/.next/server/chunks/7884.js:71:79472
    at /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:185493
    at /var/task/.next/server/chunks/7884.js:71:80320 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/var/task/messages/en'
}
```

Then many errors such as
```
u [Error]: MISSING_MESSAGE: home.metadata (en)
    at /var/task/.next/server/chunks/7884.js:76:37071
    at t.createBaseTranslator (/var/task/.next/server/chunks/7884.js:76:37121)
    at /var/task/.next/server/chunks/7884.js:76:35140
    at t.eX (/var/task/.next/server/chunks/7884.js:76:35192)
    at /var/task/.next/server/chunks/7884.js:71:80338
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.f (/var/task/.next/server/app/[locale]/page.js:1:4229) {
  code: 'MISSING_MESSAGE',
  originalMessage: 'home.metadata (en)'
}
```

It works perfectly locally though ...

Any ideas how to fix this?
Cheers

**Comment by HPouyanmehr** [comment]
Hey @pmarxbraun, thank you for reporting this. 

This issue happens because Vercel's deployment environment is serverless, meaning that files and directories outside of the `/public` folder are not available at runtime. That's why you're seeing errors when trying to access files. A quick fix (but maybe a bit dirty) is to move translations into the `/public` folder.

Generally, this is not an issue in `next-intl-split` as the package can properly work on other servers. But because Vercel is a suitable place for deploying Next.js projects, I'll check for a solution for the production version in my free time. Maybe I could create a single JSON file at build time🤔

**Comment by HPouyanmehr** [comment]
It's now possible to deploy to the Vercel without having the previous issue. 

Check the example code ([Demo](https://next-intl-split.vercel.app/en)) 

I recommend to check the [README](https://github.com/HPouyanmehr/next-intl-split) file. Here is what you need to do after updating to the `@latest`:
1. Edit the `next.config.js`. [check out here](https://github.com/HPouyanmehr/next-intl-split/tree/main?tab=readme-ov-file#next-config-only-for-serverless-deployment-environments)
2. Edit the `getRequestConfig`. [check out here](https://github.com/HPouyanmehr/next-intl-split/tree/main?tab=readme-ov-file#request-config-serverless-environment-like-vercel)
3. Make sure to build once before deployment

I'm going to close this, but feel free to add comments or open it again.

**Comment by pmarxbraun** [comment]
Thanks @HPouyanmehr I'll give it a try
